---
- name: Create longhorn Namespace
  kubernetes.core.k8s:
    name: "{{ longhorn_namespace }}"
    kind: Namespace
    state: present
    kubeconfig: "{{ kube_config }}"
  tags: longhorn
- name: Make longhorn namespace privileged
  kubernetes.core.k8s:
    state: patched
    kind: Namespace
    name: "{{ longhorn_namespace }}"
    kubeconfig: "{{ kube_config }}"
    definition:
      metadata:
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged
  tags: longhorn
- name: Add longhorn helm repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
  tags: longhorn
- name: Install longhorn
  kubernetes.core.helm:
    chart_ref: longhorn/longhorn
    state: "{{ longhorn_state }}"
    release_namespace: "{{ longhorn_namespace }}"
    name: longhorn
    kubeconfig: "{{ kube_config }}"
    update_repo_cache: true
    wait: "{{ helm_wait }}"
    wait_timeout: "{{ longhorn_wait_timeout }}"
    chart_version: "{{ longhorn_version }}"
    values:
      defaultSettings:
        createDefaultDiskLabeledNodes: true
        defaultDataPath: /mnt/longhorn
        defaultReplicaCount: "{{ longhorn_default_replica_count }}"
        priorityClass: high-priority
        upgradeChecker: true
        nodeDrainPolicy: "{{ longhorn_node_drain_policy }}"
        guaranteedInstanceManagerCPU: "{{ longhorn_guaranteed_instance_manager_cpu }}"
        fastReplicaRebuildEnabled: "{{ longhorn_fast_replica_rebuild_enabled }}"
        snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: "{{ longhorn_snapshot_data_int_check_after_creation }}"
  tags: longhorn
