apiVersion: v1
kind: Pod
metadata:
  name: task-pv-inspect
  namespace: <replace-with-pvc-namespace>
spec:
  nodeName: <replace-with-node-name>
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: <replace-with-claim-name>
  containers:
    - name: task-pv-container
      image: busybox
      volumeMounts:
        - mountPath: "/pvc"
          name: pvc
      command:
      - sleep
      - "infinity"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
