- name: Add Kiali Helm Repo
  tags: istio
  kubernetes.core.helm_repository:
    name: kiali
    repo_url: https://kiali.org/helm-charts
- name: Install Kiali
  tags: istio
  kubernetes.core.helm:
    chart_ref: kiali/kiali-operator
    release_namespace: istio-system
    name: kiali
    kubeconfig: "{{ kube_config }}"
    update_repo_cache: true
    wait: "{{ helm_wait }}"
    state: "{{ istio_kiali_state }}"
    values:
      cr:
        create: true
        namespace: istio-system
        spec:
          istio_namespace: istio-system
          auth:
            strategy: anonymous
          external_services:
            grafana:
              enabled: true
              in_cluster_url: http://prom-grafana.prometheus.svc.cluster.local:80/
              url: http://prom-grafana.prometheus.svc.cluster.local:80/
            prometheus:
              url: http://prom-kube-prometheus-stack-prometheus.prometheus.svc.cluster.local:9090/
            tracing:
              enabled: true
              in_cluster_url: http://jaeger-query.jaeger.svc.cluster.local:16685/jaeger
              use_grpc: true