---
- name: Create couchdb Namespace
  kubernetes.core.k8s:
    name: "{{ couchdb_namespace }}"
    kind: Namespace
    state: present
    kubeconfig: "{{ kube_config }}"
  tags: couchdb
- name: Make couchdb namespace privileged
  kubernetes.core.k8s:
    state: patched
    kind: Namespace
    name: "{{ couchdb_namespace }}"
    kubeconfig: "{{ kube_config }}"
    definition:
      metadata:
        labels:
          pod-security.kubernetes.io/enforce: restricted
          pod-security.kubernetes.io/audit: restricted
          pod-security.kubernetes.io/warn: restricted
  tags: couchdb
- name: Add couchdb Helm Repo
  kubernetes.core.helm_repository:
    name: couchdb
    repo_url: https://apache.github.io/couchdb-helm/
  tags: couchdb
- name: Install couchdb
  tags: couchdb
  kubernetes.core.helm:
    chart_ref: couchdb/couchdb
    state: "{{ couchdb_state }}"
    release_namespace: "{{ couchdb_namespace }}"
    name: couchdb
    kubeconfig: "{{ kube_config }}"
    update_repo_cache: true
    wait: "{{ helm_wait }}"
    wait_timeout: "{{ couchdb_wait_timeout }}"
    chart_version: "{{ couchdb_version }}"
