---
- name: Create kyverno Namespace
  kubernetes.core.k8s:
    name: "{{ kyverno_namespace }}"
    kind: Namespace
    state: present
    kubeconfig: "{{ kube_config }}"
  tags: kyverno
- name: Make kyverno namespace privileged
  kubernetes.core.k8s:
    state: patched
    kind: Namespace
    name: "{{ kyverno_namespace }}"
    kubeconfig: "{{ kube_config }}"
    definition:
      metadata:
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged
  tags: kyverno
- name: Add kyverno Helm Repo
  kubernetes.core.helm_repository:
    name: kyverno
    repo_url: https://kyverno.github.io/kyverno/
  tags: kyverno
- name: Install kyverno
  tags: kyverno
  kubernetes.core.helm:
    chart_ref: kyverno/kyverno
    state: "{{ kyverno_state }}"
    release_namespace: "{{ kyverno_namespace }}"
    name: kyverno
    kubeconfig: "{{ kube_config }}"
    update_repo_cache: true
    wait: "{{ helm_wait }}"
    wait_timeout: "{{ kyverno_wait_timeout }}"
    chart_version: "{{ kyverno_version }}"
