---
all:
  vars:
    timezone: UTC
  children:
    # where kubectl and helm commands run
    controller:
      hosts:
        controller1:
          kube_config: /etc/rancher/k3s/k3s.yaml
          helm_wait: true
          longhorn_storage_classes_manages_default_sc: true
          longhorn_storage_classes_default_sc: ssd
          longhorn_storage_classes_secrets:
            - name: mechnical
              namespace: longhorn-system
              state: present
              hash: sha256
              pbkdf: argon2i
              cipher: aes-xts-plain64
              size: "256"
              provider: secret
              key: changeit
            - name: ssd
              namespace: longhorn-system
              state: present
              hash: sha256
              pbkdf: argon2i
              cipher: aes-xts-plain64
              size: "256"
              provider: secret
              key: changeit
          longhorn_storage_classes_sc:
            - name: ssd
              allowVolumeExpansion: true
              reclaimPolicy: Retain
              volumeBindingMode: Immediate
              replicas: "1"
              staleReplicaTimeout: "2880"
              encrypted: "true"
              fsType: ext4
              diskSelector: ssd
              nodeSelector: ""
              dataLocality: disabled
              mkfsParams: ""
              mountOptions: []
              migratable: "false"
              recurringJobsSelector: ""
              nfsOptions: ""
              secretName: ssd
              secretNamespace: longhorn-system
              state: present
            - name: mechnical
              allowVolumeExpansion: true
              reclaimPolicy: Retain
              volumeBindingMode: Immediate
              replicas: "1"
              staleReplicaTimeout: "2880"
              encrypted: "true"
              fsType: ext4
              diskSelector: slow
              nodeSelector: ""
              dataLocality: disabled
              mkfsParams: ""
              mountOptions: []
              migratable: "false"
              recurringJobsSelector: ""
              nfsOptions: ""
              secretName: mechnical
              secretNamespace: longhorn-system
              state: present
          longhorn_disks_config:
            - node: disk-node-1
              config:
                - name: disk-1
                  path: /mnt/longhorn/disk-1
                  allowScheduling: true
                  tags:
                    - ssd
                    - fast
            - node: disk-node-1
              config:
                - name: disk-1
                  path: /mnt/longhorn/disk-2
                  allowScheduling: true
                  tags:
                    - slow
                    - large
    server:
      hosts:
        controller1:
          k3s_run_cluster_init: true
        controller2:
        controller3:
    agent:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
        node6:
        node7:
        node8:
        node9:
    k3s_cluster:
      vars:
        # store in a vault, just for example
        token: changeit
        # can be a primary hostname or a hostname that use dns load balancing for the servers
        api_endpoint: somename
        k3s_version: v1.28.2+k3s1
        k3s_run_cluster_init: false
        ansible_user: ansible
        systemd_dir: /etc/systemd/system
      children:
        agent:
        server:
    raspberrypi:
      hosts:
        pi1:
        pi2:
        pi3:
        pi4:
        pi5:
        pi6:
        pi7:
        pi8:
        pi9:
        pi10:
