---
- name: Create cilium Namespace
  kubernetes.core.k8s:
    name: "{{ cilium_namespace }}"
    kind: Namespace
    state: present
    kubeconfig: "{{ kube_config }}"
  tags: cilium
- name: Make cilium namespace privileged
  kubernetes.core.k8s:
    state: patched
    kind: Namespace
    name: "{{ cilium_namespace }}"
    kubeconfig: "{{ kube_config }}"
    definition:
      metadata:
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged
  tags: cilium
- name: Add Cilium Helm Repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
  tags: cilium
- name: Install Cilium
  tags: cilium
  kubernetes.core.helm:
    chart_ref: cilium/cilium
    state: "{{ cilium_state }}"
    release_namespace: cilium
    name: cilium
    kubeconfig: "{{ kube_config }}"
    update_repo_cache: true
    wait: "{{ helm_wait }}"
    wait_timeout: "{{ cilium_wait_timeout }}"
    chart_version: "{{ cilium_version }}"
    values:
      cni:
        exclusive: false
      ipv4NativeRoutingCIDR: "{{ cilium_ipv4NativeRoutingCIDR }}"
      ipv6NativeRoutingCIDR: "{{ cilium_ipv6NativeRoutingCIDR }}"
      k8sServiceHost: "{{ api_endpoint }}"
      k8sServicePort: "{{ api_port | default(6443) }}"
      l7Proxy: false
      endpointRoutes:
        enabled: false
      enableIPv4Masquerade: true
      enableIPv6Masquerade: true
      bpf:
        masquerade: false
      ipv4:
        enabled: true
      ipv6:
        enabled: true
      encryption:
        enabled: true
        type: wireguard
        nodeEncryption: true
        wireguard:
          userspaceFallback: true
      containerRuntime:
        integration: containerd
        socketPath: /var/run/k3s/containerd/containerd.sock
      hubble:
        relay:
          enabled: true
        ui:
          enabled: true
      kubeProxyReplacement: true
      socketLB:
        hostNamespaceOnly: true
- name: Wait for CRDs to be available
  tags:
    - cilium
  ansible.builtin.command: kubectl -n {{ cilium_namespace }} wait --for condition=established --timeout=5s crd/ciliumnetworkpolicies.cilium.io
  register: crd_status
  until: crd_status.rc == 0
  retries: 7
  delay: 1
  changed_when: false
