---
- name: Manage Cluster Monitoring
  hosts: controller
  become: true
  roles:
    - role: open_search
      when: open_search_enabled
    - role: prometheus
      when: prometheus_enabled
    - role: jaeger
      when: jaeger_enabled
    - role: kiali
      when: kiali_enabled
    - role: couchdb
      when: couchdb_enabled
    - role: syslog_portal
      when: syslog_portal_enabled
