---
- name: Manage Cluster Monitoring
  hosts: controller
  become: true
  roles:
    - role: elastic_search
    - role: prometheus
    - role: jaeger
    - role: kiali
    - role: couchdb
    - role: syslog_portal
