---
- name: Manage Cluster Apps
  hosts: controller
  become: true
  roles:
    - role: registry
      when: registry_enabled
    - role: plex
      when: plex_enabled
    - role: openmct
      when: openmct_enabled
