---
- name: Get information on hostnames and users
  hosts: all
  tasks:
    - name: Get ansible user on remote system
      ansible.builtin.debug:
        msg: current user is {{ ansible_user_id }}
    - name: Get hostname of remote system
      ansible.builtin.debug:
        msg: current host is {{ ansible_hostname }}
