---
- name: Manage GitHub Runners
  hosts: github_runners
  become: false
  roles:
    - role: github_runner
      tags:
        - github-runner
    - role: rootless_containerd
      tags:
        - rootless-containerd
      vars:
        rootless_containerd_users:
          - user: github
  