---
- hosts: managed_netplans
  gather_facts: true
  become: true
  roles:
    - role: netplan
      become: true
      netplan_enabled: true
      netplan_config_file: /etc/netplan/50-cloud-init.yaml
      netplan_renderer: networkd
      netplan_configuration:
        network:
          version: 2
          ethernets:
            eth0:
              dhcp6: false
              dhcp6-overrides:
                use-dns: false
              dhcp4: true
              dhcp4-overrides:
                use-dns: false
              accept-ra: true
              optional: false
              ipv6-privacy: true
              nameservers:
                search: []
                addresses: "{{ netplan_dns_servers }}"
    - role: secure_dns
      become: true
