---
- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: mrlesmithjr.netplan
      become: true
      netplan_enabled: true
      netplan_config_file: /etc/netplan/50-cloud-init.yaml
      netplan_renderer: networkd
      netplan_configuration:
        network:
          version: 2
          ethernets:
            eth0:
              dhcp6: false
              dhcp6-overrides:
                use-dns: no
              dhcp4: true
              dhcp4-overrides:
                use-dns: no
              accept-ra: true
              optional: false
              ipv6-privacy: true
              nameservers:
                search: []
                addresses:
                  - '1.1.1.1'
                  - '1.0.0.1'
                  - '2606:4700:4700::1111'
