---
- name: Get Effective ID
  become: true
  become_user: "{{ item.user }}"
  ansible.builtin.command: id -ru
  changed_when: false
  register: rootless_containerd_effective_id
- name: Setup rootless containerd
  become: true
  become_user: "{{ item.user }}"
  ansible.builtin.command: containerd-rootless-setuptool.sh install
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ rootless_containerd_effective_id.stdout }}"
- name: Setup rootless containerd buildkit
  become: true
  become_user: "{{ item.user }}"
  ansible.builtin.command: containerd-rootless-setuptool.sh install-buildkit
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ rootless_containerd_effective_id.stdout }}"
- name: Enable linger for user
  become: true
  ansible.builtin.command: "loginctl enable-linger {{ item.user }}"
- name: Alias nerdctl to docker
  become: true
  ansible.builtin.lineinfile:
    dest: "/home/{{ item.user }}/.bashrc"
    create: yes
    mode: 0644
    line: 'alias docker=nerdctl'
    regexp: "^alias docker="
