---
- name: Create openfaas Namespace
  kubernetes.core.k8s:
    name: "{{ openfaas_namespace }}"
    kind: Namespace
    state: present
    kubeconfig: "{{ kube_config }}"
  tags: openfaas
- name: Create openfaas-fn namespace
  kubernetes.core.k8s:
    name: "{{ openfaas_namespace }}-fn"
    kind: Namespace
    state: present
    kubeconfig: "{{ kube_config }}"
  tags: openfaas
- name: Make openfaas namespace privileged
  kubernetes.core.k8s:
    state: patched
    kind: Namespace
    name: "{{ openfaas_namespace }}"
    kubeconfig: "{{ kube_config }}"
    definition:
      metadata:
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged
  tags: openfaas
- name: Make openfaas-fn namespace privileged
  kubernetes.core.k8s:
    state: patched
    kind: Namespace
    name: "{{ openfaas_namespace }}-fn"
    kubeconfig: "{{ kube_config }}"
    definition:
      metadata:
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged
- name: Add openfaas Helm Repo
  kubernetes.core.helm_repository:
    name: openfaas
    repo_url: https://openfaas.github.io/faas-netes
  tags: openfaas
- name: Install openfaas
  tags: openfaas
  kubernetes.core.helm:
    chart_ref: openfaas/openfaas
    state: "{{ openfaas_state }}"
    release_namespace: "{{ openfaas_namespace }}"
    name: openfaas
    kubeconfig: "{{ kube_config }}"
    update_repo_cache: true
    wait: "{{ helm_wait }}"
    wait_timeout: "{{ openfaas_wait_timeout }}"
    chart_version: "{{ openfaas_version }}"
    values:
      functionNamespace: "{{ openfaas_namespace }}-fn"
