---
- name: Manage longhorn disk configurations
  kubernetes.core.k8s:
    state: patched
    kind: Node
    name: "{{ item.node }}"
    kubeconfig: "{{ kube_config }}"
    definition:
      metadata:
        annotations:
          node.longhorn.io/default-disks-config: "{{ item.config | to_json }}"
        labels:
          longhorn-enabled: "true"
  loop: "{{ longhorn_disks_config }}"
